"""
.. module:: ontology

 Translated by owl2rdflib

 Translated to RDFlib from ontology http://www.semanticweb.org/eric/ontologies/2021/4/ecsdiOntology

 :Date 06/06/2021 20:29:11
"""
from rdflib import URIRef
from rdflib.namespace import ClosedNamespace

ECSDI = ClosedNamespace(
    uri=URIRef('http://www.semanticweb.org/eric/ontologies/2021/4/ecsdiOntology'),
    terms=[
        # Classes
        'Agente_Recomendacion',
        'Localizacion',
        'Agente_Externo_Vuelos',
        'Agente_Externo_Alojamientos_Amadeus',
        'Festiva',
        'Servicio',
        'Peticion_de_plan',
        'Agente_Viaje',
        'Respuesta_Valoracion',
        'Ciudad',
        'Respuesta_Actividades',
        'Lúdica',
        'Aeropuerto',
        'Plan_de_dia',
        'Agente_Externo_Vuelos_Amadeus',
        'Proveedor_de_vuelos',
        'Vuelo',
        'Respuesta_Tiempo',
        'Alojamiento',
        'Peticion_Alojamientos',
        'Peticion',
        'Compania',
        'Agente_Externo_Actividades_Amadeus',
        'Respuesta',
        'Plan_de_viaje',
        'Documento',
        'Agente_Opinion',
        'Agente_Vuelos',
        'Proveedor_de_actividades',
        'Recibo',
        'Usuario',
        'Peticion_Vuelos',
        'Agente_Pagos',
        'Agente_Actividades',
        'Cultural',
        'Comunicacion',
        'Factura',
        'Directory',
        'Respuesta_Alojamiento',
        'Respuesta_Plan',
        'Agente',
        'Tiempo_meteorologico',
        'Valoracion',
        'Peticion_Actividades',
        'Agente_Alojamientos',
        'Peticion_Tiempo',
        'Proveedor_alojamiento',
        'Actividad',
        'Respuesta_Vuelos',
        'Plan',
        'Lugar',
        'Peticion_Valoracion',

        # Object properties
        'tiene_actividades',
        'tiene_como_aeropuerto_origen',
        'ofrece_vuelo',
        'genera',
        'ofrece_actividades',
        'opina_sobre',
        'provoca',
        'llega_a',
        'contiene',
        'se_recomienda_a',
        'es_ofrecido_por',
        'tiene_para_cada_dia',
        'solicita',
        'tiene_recibo',
        'tiene_como_vuelo_de_vuelta',
        'tiene_factura',
        'tiene_localizacion_como_restriccion',
        'envia',
        'hace',
        'tiene_como_vuelo_de_ida',
        'esta_hecha_por',
        'tiene_como_aeropuerto_destino',
        'tiene_ubicación',
        'tiene_como_alojamiento',
        'contrata',

        # Data properties
        'puntuacion',
        'rango_precio_transporte_min',
        'id_actividad',
        'id_vuelo',
        'id_plan',
        'coordenadas',
        'porcentaje_actividad_ludica',
        'porcentaje_actividad_cultural',
        'franja_horaria',
        'fecha_final',
        'importe',
        'ciudad',
        'nombre',
        'rango_precio_transporte_max',
        'Archivo',
        'ciudad_origen',
        'ciudad_destino',
        'porcentaje_actividad_festiva',
        'rango_precio_alojamiento_max',
        'fecha_inicial',
        'tiempo',
        'centrico',
        'rango_precio_alojamiento_min',
        'id_alojamiento'

        # Named Individuals
    ]
)